DATA:
  DATASET: camelyon16
  IMG_SIZE: 672
  NUM_WORKERS: 10
MODEL:
  TYPE: swin
  NUM_CLASSES : 2
  NAME: giga_patch16_stride6_window7_672
  DROP_PATH_RATE: 0.5
  SWIN:
    PATCH_SIZE: 16
    EMBED_DIM: 96
    DEPTHS: [ 9 ]
    NUM_HEADS: [ 6 ]
    WINDOW_SIZE: 7
TEST:
  CROP : False
  RETAIN: True